# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e619deb6c4d9014faeee4f9639afa05937bdfadf4d940a02b892d6ab56b6c7b9fa746cf36ccb8d4f436857a7b1f41beb8a96991e18a55d4e8622e54ee03c777

test:
  secret_key_base: 7b4f1136573ce595d26223e94f9eb5e701b1e45939f86b9f7894bb75ff44c62bd5f8c877896774190c224a410a885560b1361a3fca76b6f25583afec46794b91

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
